# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/GraphFormer',
                'doc_host': 'https://Techolution.github.io',
                'git_url': 'https://github.com/Techolution/GraphFormer',
                'lib_path': 'GraphFormer'},
  'syms': {'GraphFormer.core': {'GraphFormer.core.foo': ('core.html#foo', 'GraphFormer/core.py')}}}
